### ISSUE TITLE
Update for 0.10?

### ISSUE THREAD

**Issue by clayrat** [purescript-contrib/purescript-foreign-lens#5]
When using latest `purescript-profunctor-lenses` and `purescript-foreign`, (after replacing `FoldP`->`Fold'`) the build fails with 

```
 No type class instance was found for                                                   

   Data.Traversable.Traversable (ExceptT (NonEmptyList ForeignError) Identity)          

 while checking that expression (compose (to readString)) traversed                     
   has type forall r. (Monoid r) => Forget r String String -> Forget r Foreign Foreign  
```

Is this a matter of adding a `Traversable` instance on `ExceptT`, or should this be rewritten in some other way?

**Comment by paf31** [comment]
Yes, I'll be updating this library soon.
